# Generated by Django 4.2.3 on 2023-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=200)),
                ('experience', models.TextField(max_length=20)),
                ('fee', models.TextField(max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='ser')),
            ],
        ),
    ]
