# Generated by Django 4.2.3 on 2023-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fee',
        ),
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
    ]
