# Generated by Django 4.2.3 on 2023-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='msg',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default='null'),
        ),
    ]
