# Generated by Django 4.2.3 on 2023-08-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_contact_description_contact_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.TextField(default='wer', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(default='abc', max_length=30),
        ),
    ]
